---
title: "Community Health Stats"
output: html_document
---

```{r echo = FALSE, message=F, warning=F}
require(ggplot2)
library(ggplot2)
library(plyr)
library(splines)
require(quantmod)
```


```{r echo=FALSE}
#Read Summary

filename <- "tomtom-en_topic_daterange_20151101_20160928_created20160929_131249.csv"
typeOfAnalysis <- "Topics"



p <- regexpr('[a-zA-Z]*-[a-zA-Z]{2}', filename)
d <- regexpr('[0-9]{8}_[0-9]{8}', filename)
envname <- regmatches(filename, p)
daterange <- regmatches(filename, d)
docpath <- paste0("data/",filename)


```


### Data Loaded
```{r echo=FALSE}

print(cat(paste0("Environment name: ",envname,"\n","Date range: ",daterange,"\n","\n","Filename: ",filename,"\n","Analysis type: ", typeOfAnalysis,"\n")))
```

```{r echo=FALSE}

#read file
df <- read.csv(docpath, stringsAsFactors=FALSE)

```


```{r echo=FALSE}
### Step 2
# Read creation data, and add new column, containing only month and year

 
df$creation_time <- as.Date(df$creation_time, format = "%d-%m-%Y")
df$creation_month <- strftime(df$creation_time, "%Y-%m")


```


```{r echo=FALSE}
### Step 3
# Aggregate dates of the posts to do a count
# posts 

#count total topics
total_topic_daily <- count(df, "creation_time")
total_topic_month <- count(df, "creation_month")
names(total_topic_daily)[2] <- 'total_topics'
names(total_topic_month)[2] <- 'total_topics'

#count total replies
total_topicreplies_daily <- aggregate(total_comments~creation_time,df,sum)
total_topicreplies_month <- aggregate(total_comments~creation_month,df,sum)
names(total_topicreplies_month)[2] <- 'total_topiccomments'

#count total topic view
total_topicview_daily <- aggregate(total_views~creation_time,df,sum)
total_topicview_month <- aggregate(total_views~creation_month,df,sum)
names(total_topicview_month)[2] <- 'total_topicviews'

#count total topic type question
df1 <- subset(df,topic_type=="Question")
total_topic_question_daily <- count(df1, "creation_time")
total_topic_question_month <- count(df1, "creation_month")
names(total_topic_question_daily)[2] <- 'total_topic_question'
names(total_topic_question_month)[2] <- 'total_topic_question'

#count total topic type solved
df1 <- subset(df,topic_type=="Solved")
total_topic_solved_daily <- count(df1, "creation_time")
total_topic_solved_month <- count(df1, "creation_month")
names(total_topic_solved_daily)[2] <- 'total_topic_solved'
names(total_topic_solved_month)[2] <- 'total_topic_solved'

#count total topic type discussion
df1 <- subset(df,topic_type=="")
total_topic_discussion_daily <- count(df1, "creation_time")
total_topic_discussion_month <- count(df1, "creation_month")
names(total_topic_discussion_daily)[2] <- 'total_topic_discussion'
names(total_topic_discussion_month)[2] <- 'total_topic_discussion'

#count total topic status visible
df1 <- subset(df,topic_status=="visible")
total_topic_visible_daily <- count(df1, "creation_time")
total_topic_visible_month <- count(df1, "creation_month")
names(total_topic_visible_daily)[2] <- 'total_topic_visible'
names(total_topic_visible_month)[2] <- 'total_topic_visible'
 
#count total topic status visible
df1 <- subset(df,topic_status=="trashed")
total_topic_trashed_daily <- count(df1, "creation_time")
total_topic_trashed_month <- count(df1, "creation_month")
names(total_topic_trashed_daily)[2] <- 'total_topic_trashed'
names(total_topic_trashed_month)[2] <- 'total_topic_trashed'

#merge all tables
summary_topics_daily <- merge(x = total_topicreplies_daily, y = total_topicview_daily, by = "creation_time", all = TRUE)
summary_topics_daily <- merge(x = total_topic_daily, y = summary_topics_daily, by = "creation_time", all = TRUE)
summary_topics_daily <- merge(x = total_topic_question_daily, y = summary_topics_daily, by = "creation_time", all = TRUE)
summary_topics_daily <- merge(x = total_topic_solved_daily, y = summary_topics_daily, by = "creation_time", all = TRUE)
summary_topics_daily <- merge(x = total_topic_discussion_daily, y = summary_topics_daily, by = "creation_time", all = TRUE)
summary_topics_daily <- merge(x = total_topic_visible_daily, y = summary_topics_daily, by = "creation_time", all = TRUE)
summary_topics_daily <- merge(x = total_topic_trashed_daily, y = summary_topics_daily, by = "creation_time", all = TRUE)

summary_topics_monthly <- merge(x = total_topicreplies_month, y = total_topicview_month, by = "creation_month", all = TRUE)
summary_topics_monthly <- merge(x = total_topic_month, y = summary_topics_monthly, by = "creation_month", all = TRUE)
summary_topics_monthly <- merge(x = total_topic_question_month, y = summary_topics_monthly, by = "creation_month", all = TRUE)
summary_topics_monthly <- merge(x = total_topic_solved_month, y = summary_topics_monthly, by = "creation_month", all = TRUE)
summary_topics_monthly <- merge(x = total_topic_discussion_month, y = summary_topics_monthly, by = "creation_month", all = TRUE)
summary_topics_monthly <- merge(x = total_topic_visible_month, y = summary_topics_monthly, by = "creation_month", all = TRUE)
summary_topics_monthly <- merge(x = total_topic_trashed_month, y = summary_topics_monthly, by = "creation_month", all = TRUE)

#replace NA value with 0, so that we can still count properly
summary_topics_daily[is.na(summary_topics_daily)] <- 0
summary_topics_monthly[is.na(summary_topics_monthly)] <- 0


```

### Summary
```{r echo=FALSE}

avg_topic <- format(mean(summary_topics_monthly[["total_topics"]]),2)
avg_topicview <- format(mean(summary_topics_monthly[["total_topicviews"]]),2)
avg_topiccomment <- format(mean(summary_topics_monthly[["total_topiccomments"]]),2)
avg_topicquestion <- format(mean(summary_topics_monthly[["total_topic_question"]]),2)
avg_topicsolved <- format(mean(summary_topics_monthly[["total_topic_solved"]]),2)
avg_topicdiscussion <- format(mean(summary_topics_monthly[["total_topic_discussion"]]),2)
avg_topicvisible <- format(mean(summary_topics_monthly[["total_topic_visible"]]),2)
avg_topictrashed <- format(mean(summary_topics_monthly[["total_topic_trashed"]]),2)

# ratio of solved question compared to all questions asked in the community
ratio_topicsolvedquestion <- format(mean(summary_topics_monthly[["total_topic_solved"]]/(summary_topics_monthly[["total_topic_question"]]+summary_topics_monthly[["total_topic_solved"]])),2)

ratio_topictrashedtopics <- format(mean(summary_topics_monthly[["total_topic_trashed"]]/summary_topics_monthly[["total_topics"]]),2)


#log_avg_pageviews <- log2(avg_pageviews)
print(cat(paste0("Average topic (month):", avg_topic,"\n","Average topic question (month): ", avg_topicquestion,"\n","Average topic solved (month): ", avg_topicsolved,"\n","Average topic discussion (month): ", avg_topicdiscussion,"\n","Average topic replies (month): ", avg_topiccomment,"\n","Average topic views (month): ", avg_topicview,"\n","Average topic visible (month): ", avg_topicvisible,"\n","Average topic trashed (month): ", avg_topictrashed,"\n")))

print(cat(paste0("Ratio of solved questions: ", ratio_topicsolvedquestion,"\n","Ratio of trashed topics: ", ratio_topictrashedtopics,"\n")))

```

```{r echo=FALSE}
### Step 4
#Do plot for login

p <- qplot(creation_time, total_topics, data=summary_topics_daily, geom=c("point", "smooth"), main="Total Topics",  xlab="month", ylab="#Topic")
print(p)

q <- qplot(creation_time, total_comments, data=summary_topics_daily, geom=c("point", "smooth"), main="Total Topics Comments",  xlab="month", ylab="#Topic Comments")
print(q)

r <- qplot(creation_time, total_views, data=summary_topics_daily, geom=c("point", "smooth"), main="Total Topics Views",  xlab="month", ylab="#Topic View")
print(r)

```

```{r echo=FALSE}

print(summary_topics_monthly)
#print(summary_topics_daily)

#write dataframe in csv file
outputfile1 <- paste0("data/",envname,"_summary_topics_monthly_",daterange,".csv")
outputfile2 <- paste0("data/",envname,"_summary_topics_daily_",daterange,".csv")
write.csv(summary_topics_monthly, file = outputfile1)
write.csv(summary_topics_daily, file = outputfile2)

```
