---
title: "Community Health Stats"
output: html_document
---

```{r echo = FALSE, message=F, warning=F}
require(ggplot2)
library(ggplot2)
library(plyr)
library(splines)
#require(quantmod)
```


```{r echo=FALSE}
#Read Summary

filename <- "vgz-nl_topic_daterange_20150101_20161007_created20161008_204417.csv"
typeOfAnalysis <- "Topics"



p <- regexpr('[a-zA-Z]*-[a-zA-Z]{2}', filename)
d <- regexpr('[0-9]{8}_[0-9]{8}', filename)
envname <- regmatches(filename, p)
daterange <- regmatches(filename, d)
docpath <- paste0("data/",filename)


```


### Data Loaded
```{r echo=FALSE}

print(cat(paste0("Environment name: ",envname,"\n","Date range: ",daterange,"\n","\n","Filename: ",filename,"\n","Analysis type: ", typeOfAnalysis,"\n")))
```

```{r echo=FALSE}

#read file
df <- read.csv(docpath, stringsAsFactors=FALSE)

```


```{r echo=FALSE}
### Step 2
# Read creation data, and add new column, containing only month and year

df[ , "creation_time"] <- df["date_creation"]

t3 <- df$date_creation
df[ , "creation_time"] <- as.POSIXct(t3, tz="Europe/Amsterdam", format="%d-%m-%Y %H:%M:%OS")

df[ , "creation_time_us"] <- format(df[ , "creation_time"], tz="US/Pacific")
#print(t1)
print(head(df))
```


```{r echo=FALSE}

#print(testdf)

#write dataframe in csv file
#outputfile1 <- paste0("data/","US_",filename)
#write.csv(df, file = outputfile1)

```
