---
title: "Community Health Stats"
output: html_document
---

```{r echo = FALSE, message=F, warning=F}
require(ggplot2)
library(ggplot2)
library(plyr)
library(splines)
require(quantmod)
```


```{r echo=FALSE}

loginfilename <- "tomtom-en_registration_daterange_20150901_20161004_created20161005_224648.csv"

p <- regexpr('[a-zA-Z]*-[a-zA-Z]{2}', loginfilename)
d <- regexpr('[0-9]{8}_[0-9]{8}', loginfilename)
envname <- regmatches(loginfilename, p)
daterange <- regmatches(loginfilename, d)
loginpath <- paste0("data/",loginfilename)

```


### Data Loaded
```{r echo=FALSE}

print(cat(paste0("Environment name: ",envname,"\n","Date range: ",daterange,"\n","\n","Registration filename: ",loginfilename,"\n")))
```

```{r echo=FALSE}

#telfort
dreg <- read.csv(loginpath, stringsAsFactors=FALSE)

```


```{r echo=FALSE}
### Step 2
# Read creation data, and add new column, containing only month and year

#for registration
dreg[ , "registration_time"] <- dreg["time"]
dreg$registration_time <- as.Date(dreg$registration_time, format = "%d-%m-%Y")
dreg$month <- strftime(dreg$registration_time, "%Y-%m")



```


```{r echo=FALSE}
### Step 3
# Aggregate dates of the posts to do a count
# posts 
daily_registration_count <- count(dreg, "registration_time")
monthly_registration_count <- count(dreg, "month")

```


### Number of total registration each month
```{r echo=FALSE}
#posts
monthly_registration_count$monthlyDiff <- c(0, diff(monthly_registration_count$freq))

monthly_registration_count$pctDiff <- monthly_registration_count$monthlyDiff/(monthly_registration_count$freq-monthly_registration_count$monthlyDiff)
monthly_registration_count$pctDiff <- paste(round(100*monthly_registration_count$pctDiff, 2), "%", sep="")

# for presentation only
monthly_registration_count2 <- monthly_registration_count
colnames(monthly_registration_count2) <- c("month", "#total registration", "monthly_difference", "%growth")

avg_reg <- mean(monthly_registration_count[["freq"]])
print(paste0("average registration is: ", avg_reg))
print(monthly_registration_count2)

```


```{r echo=FALSE}
### Step 4
#Do plot for login

p <- qplot(registration_time, freq, data=daily_registration_count, geom=c("point", "smooth"), main="#Total registration",  xlab="month", ylab="#registration")
print(p)

q <- qplot(month, freq, data=monthly_registration_count, geom=c("point", "smooth"), main="#Total registration",  xlab="month", ylab="#registration")
print(q)

#r <- hist(dreg$month, breaks = 40)
#print(r)

counts <- table(dreg$month)
r <- barplot(counts, main="Car Distribution by Gears and VS",
  xlab="Number of Gears", col=c("blue"))
print(r)

```

